version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dojo
      POSTGRES_PASSWORD: dojo
      POSTGRES_DB: dojo_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://dojo:dojo@db/dojo_dev
    ports:
      - "8080:8080"

volumes:
  db-data:

